/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "src/inverter.v:4" *)
module inverter(in, out);
  (* src = "src/inverter.v:5" *)
  input in;
  (* src = "src/inverter.v:6" *)
  output out;
  sky130_fd_sc_hd__clkinv_1 _0_ (
    .A(in),
    .Y(out)
  );
endmodule
