/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

(* top =  1  *)
(* src = "inverter.v:3.1-8.10" *)
module inverter(in, out);
  (* src = "inverter.v:4.17-4.19" *)
  wire _0_;
  (* src = "inverter.v:5.17-5.20" *)
  wire _1_;
  (* src = "inverter.v:4.17-4.19" *)
  input in;
  wire in;
  (* src = "inverter.v:5.17-5.20" *)
  output out;
  wire out;
  sky130_fd_sc_hs__clkinv_1 _2_ (
    .A(_0_),
    .Y(_1_)
  );
  assign _0_ = in;
  assign out = _1_;
endmodule
